### ISSUE TITLE
Cron Daemon email every 5 minutes after upgrading to latest version

### ISSUE THREAD

**Issue by georgetasioulis** [acronis/acronis-cyber-cloud-whmcs#4]
Hello,

Today I upgraded the Acronis WHMCS module from v2.1.1-141 to v2.2.0-175 on my WHMCS 7.10.2 installation.
No other changes were made except for the Acronis module upgrade itself.

Right after uploading the new files, I started receiving an email every 5 minutes from the Cron Daemon related to the WHMCS cron (`php -q /home/[whmcs_install_path]/crons/cron.php`)

```
Console Tool

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                    Displays help for a command
  list                    Lists commands
 usage-report
  usage-report:erase      Command for usage reports erasing, keeping only reports for last "2" days.
  usage-report:flushall   Command for usage report flushing.
  usage-report:master     Usage report aggregation master command.
  usage-report:metrics    Command for metrics fetching.
  usage-report:process    Command for usage report processing.
  usage-report:view-list  Command for usage report listing.
X-Powered-By: PHP/7.3.23
Content-Type: text/html; charset=utf-8
Set-Cookie: WHMCS5tRbx3LY=f513f0e5d2f6xa5982; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache

Console Tool

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                    Displays help for a command
  list                    Lists commands
 usage-report
  usage-report:erase      Command for usage reports erasing, keeping only reports for last "2" days.
  usage-report:flushall   Command for usage report flushing.
  usage-report:master     Usage report aggregation master command.
  usage-report:metrics    Command for metrics fetching.
  usage-report:process    Command for usage report processing.
  usage-report:view-list  Command for usage report listing.
X-Powered-By: PHP/7.3.23
Content-Type: text/html; charset=utf-8
Set-Cookie: WHMCS5tRx3LY=bbb53eb78xb66153; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
```

It's probably related to the new Metric Statistics, but those don't work either.
Any ideas?

Thanks,
George

**Comment by georgetasioulis** [comment]
Not sure if it helps, but this is what the log shows when the cron runs:
```
2020-10-19 19:55:02 c9e39b8 DEBUG Start dispatching /home/[whmcs_path]/includes/hooks/acroniscloud.php:acroniscloud_AfterCronJob. Parameters: [] File: /home/[whmcs_path]/includes/acroniscloud/lib/Service/Dispatcher/Dispatcher.php:45
2020-10-19 19:55:02 c9e39b8 NOTICE hook: afterCronJob | Running Master command File: /home/[whmcs_path]/modules/servers/acroniscloud/lib/Controller/Report.php:52
2020-10-19 19:55:02 c9e39b8 DEBUG Database query: select * from `tblservers` where `type` = ? and `disabled` = ? Bindings: ["acroniscloud",false] File: /home/[whmcs_path]/includes/acroniscloud/lib/Service/Logger/DatabaseLogging.php:60
2020-10-19 19:55:05 c9e39b8 NOTICE hook: afterCronJob COMPLETE File: /home/[whmcs_path]/modules/servers/acroniscloud/lib/Controller/Report.php:57
2020-10-19 19:55:05 c9e39b8 DEBUG End dispatching /home/[whmcs_path]/includes/hooks/acroniscloud.php:acroniscloud_AfterCronJob. Result: null File: /home/[whmcs_path]/includes/acroniscloud/lib/Service/Dispatcher/Dispatcher.php:56
```

I also added 
```
usage_report:
  download_path: tmp/reports
  downloaded_files_ttl_in_days: 2
  retries_limit: 2
  retry_timeout: 300
```
to my config.yaml but nothing gets written in the `download_path`. Also tried a couple of paths (both absolute and relative) that are for sure writable by the webserver user, but no luck.

**Comment by merx3** [comment]
Hi George,

We will investigate this, as the feature shouldn't be running in case of usage report is being disabled (not present in our config.yaml).

For now, if you don't plan on using the metrics statistic feature, I'd suggest you revert the usage_report settings you added, as the reports need some additional setup steps. 

As for the cron job, we will check why these messages show, but you should be able to comment the related daily cron jobs for the usage report hooks and that should stop the related usage report job from working while we investigate why this inconvenience is happening for you. This is just to temporarily disable the usage fetching job.
To do that, go to file `[whmcs_path]/includes/hooks/acroniscloud.php` and comment the two cron job hooks:
`$hooks = [
    'ServerAdd',
    'ServerDelete',
    'ServerEdit',
    'ClientEdit',
    'ProductEdit',
    'ServiceDelete',
    'AdminAreaHeaderOutput',
    'ClientAreaHeaderOutput',
    'OrderProductUpgradeOverride',
    'AfterModuleChangePackageFailed',
//    'AfterCronJob',
//    'DailyCronJob'
];`

Please, tell me if this resolved your issue for now.

Best regards,
Marian

**Comment by georgetasioulis** [comment]
Hi Marian,

Thank you, I can confirm that commenting the two new cron job hooks stopped the emails every 5 minutes.

I have also removed the `usage_report` stanza from my config.yaml for now (although that didn't have any effect to the cron emails - whether I had it or not, the cron email would be sent every 5 minutes), until there's more information about how to correctly enable the metrics statistic feature.

George

**Comment by merx3** [comment]
Just to clarify, this is a short-term solution, since extracting another version will overwrite the file.
We'll investigate what could cause these messages during cron runs, but for now at least they will not bother you.

Marian

**Comment by JOEsDC-Seth** [comment]
Hi George. I have observed similar info in logs / cron emails and identified that to be the output of "manage.php" when the usage_report path was invalid. Something that may not be apparent is that download_path is expected to be inside of the /includes/acroniscloud directory. With the default config.yaml options, you would need to create a writable /includes/acroniscloud/tmp/reports directory in order for usage reports to work (which is required for usage billing metrics to get updated).

I would caution you to secure the /includes/acroniscloud directory first however (with an .htaccess file for example), as the reports directory will be a publicly accessible path. I have opened issue #6 on ways we could further secure that directory as well.

**Comment by JOEsDC-Seth** [comment]
I also would like to mention why there are HTTP headers showing up in that command line output. When the 5 minute cron runs, a separate "manage.php" process gets created by this module in order to download the usage report. This is why using "php -q" did not prevent the headers from showing up when you ran the cron (a separate php process was created). The command the module uses for calling php is essentially "/usr/bin/env php". This will run the php-cli command on most systems (which does not return headers), however php-cgi may get executed instead on some servers. Adding "-q" to the process control that launches php should resolve this issue (see 1dfb8f818f5d60d65dd6d93b21178ff464f0ea28).

**Comment by georgetasioulis** [comment]
Hi Seth, 
Indeed I have created a writeable `tmp/reports` directory inside my `/includes/acroniscloud` folder but unfortunately this didn't help - metrics are still not working and cron emails still arrive every 5 minutes unless I comment those two lines.

I also tried https://github.com/JOEsDC-Seth/acronis-cyber-cloud-whmcs/commit/cad9d74054404f84c2268c5cc512b319966e36fb and specified an absolute path in config.yaml (again verified that it's writable) but that doesn't get populated either. The cron emails still arrive every 5 minutes with the same command line output.

I'm guessing that the command line in `vendor/acronis/ci-lib-php-usage-report/src/Console/Command/Master.php` is missing something. Maybe it's the datacenter ID as I don't recall providing this anywhere. I checked my WHMCS database for anything related in the acronis tables but couldn't find something. Unfortunately I have no PHP knowledge in order to investigate further, but I have an open case with mspsupport regarding this matter - I hope hey will provide a fix soon.

PS: Adding `-q` did stop the HTTP headers in the cron output, the weird thing is that running `/usr/bin/env php -v` shows that it's the php-cli binary, yet HTTP headers were shown. I changed the shebang in manage.php to `#!/usr/local/bin/php` to see if it changes anything.

**Comment by georgetasioulis** [comment]
Turns out `/usr/bin/env php` was indeed using the cgi binary, not cli:
```
PHP 7.3.23 (cgi-fcgi) (built: Oct  1 2020 15:02:37)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.3, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.23, Copyright (c) 1999-2018, by Zend Technologies
```

I've hardcoded `/usr/local/bin/php` into `vendor/acronis/ci-lib-php-usage-report/src/Console/Command/Master.php` in line 90, and now I don't get any cron emails every 5 minutes (although I don't believe it's actually working).
Then I manually ran `php manage.php usage-report:master` and for the first time the reports folder got populated and the `acroniscloud_service_reports` table in WHMCS's database has some entries now.
Now I also see the `datacenter_id` in the database. After that I ran:
```
php manage.php usage-report:metrics
php manage.php usage-report:process 23
php manage.php usage-report:process 27
```
and with `php manage.php usage-report:view-list` I see this:
```
List of reports:
+----+------------+-----------------------------------------+---------------+----------------------+------------------------------------------------------+
| ID | Date       | Datacenter name                         | Datacenter ID | Report status        | File path                                            |
+----+------------+-----------------------------------------+---------------+----------------------+------------------------------------------------------+
| 1  | 2020-11-04 | Acronis 1                               | 23            | Downloaded and saved | /xxxxxx/reports/2020-11-04/1.csv.gz |
| 2  | 2020-11-04 | Acronis 2                               | 27            | Downloaded and saved | /xxxxxx/reports/2020-11-04/2.csv.gz |
+----+------------+-----------------------------------------+---------------+----------------------+------------------------------------------------------+

```

Unfortunately still no values in the "Metric Statistics" section of any client's Acronis service, even though I can find values for eg `pg_storage_acronis` when searching the `acroniscloud_service_report_storage` table inside the `value` column using a client's tenant ID, but we're slowly getting there 👍

**Comment by JOEsDC-Seth** [comment]
Understood, thank you for the additional info. I will have some more info for you later this evening when I have more time, but there are a few things you might try in the mean time.

First, try opening one of those csv.gz reports directly in a text editor without uncompressing it. Does it actually appear to be a bunch of raw binary data, or is there one line of plain text there instead? If it's the latter, try increasing the retry timeout in your config.yaml. I set mine to 12 retries and left the default at 300 seconds per try.

Another thing you might try is to flush the existing reports with the manage.php usage-report:flushall command and then run the master command again. There is no need to run usage-report:metrics or usage-report:process [ID], as usage-report:master does everything automatically. I'll elaborate more on what is happening here as soon as I have time (and probably open a separate issue about this).

**Comment by JOEsDC-Seth** [comment]
One other thing to keep in mind is that WHMCS only updates usage metrics every 12 hours. The time it does this is somewhat arbitrary: it runs immediately after you first update to WHMCS v7.9+ then runs every 12 hours from the time it ran. The only way I have seen to change this time is from the database, by manually editing the TenantUsageMetrics `next_due` in the `tbltask_status` table. Here some SQL you can use to find out when your metrics task is scheduled to run:

```
SELECT s.id,t.class_name,t.description,s.created_at,s.last_run,s.next_due,CONCAT(t.frequency,' minutes') AS run_every
FROM tbltask AS t JOIN tbltask_status AS s ON t.id=s.task_id
WHERE t.class_name LIKE '%TenantUsageMetrics%'
```

You can also [manually run](https://docs.whmcs.com/Crons#Task_Options_for_skip_and_do) the usage metrics cron with the following command:
`php -q /home/[whmcs_install_path]/crons/cron.php do --TenantUsageMetrics -vvv`
The -vvv is optional, as it just enables the maximum level of verbosity for debugging purposes

**Comment by georgetasioulis** [comment]
So it looks like either manually specifying `/usr/local/bin/php` in the manage.php shebang and `/vendor/acronis/ci-lib-php-usage-report/src/Console/Command/Master.php`, or running `php manage.php usage-report:master` manually one time, did the trick.
Metrics are now shown in WHMCS too, in each customer's service page.

On per-GB licensed accounts, I see that 
a) it's not counting the number of licenses (https://a.cl.ly/v1uxGqEj) and 
b) as we're using Acronis storage, it's correctly identified as Per GB: Cyber Backup Cloud Standard - Acronis hosted storage (https://a.cl.ly/QwukyJ81)

On per-workload licensed accounts where we use our own Cyber Infrastructure cluster for storage, again:
a) it's not counting the number of licenses (https://a.cl.ly/bLuw2rRn) and 
b) our own storage is considered "Cloud storage" instead of "Partner storage" https://a.cl.ly/JrugYvgj
I think the latter is probably related to #8 
I will try to apply your fix, then flush the metrics. I'll then leave it to see if after 12 hours the metrics get generated (which would mean hardcoding the php-cli binary fixed the issue) or if I still need to run the master command manually the first time.

Thanks for all your input in this @JOEsDC-Seth, it's been great help!

**Comment by merx3** [comment]
Hello, 
After reviewing your comment thread, we decided to add an option in acronis config file (config.yaml) to support changing the interpreter used to process the php usage reports, as it seems symfony's console command isn't fully compatible with the php-cgi interpreter, which some clients have setup for the "php" command.

If you encounter this issue, please make sure that you've added the usage reports section in the config.yaml and set up a valid php-cli interpreter path.

This should resolve the cron job emails issue. As for the calculation inaccuracies, we have updated the usage reports to be aware of non-platform owned offering items, so the calculations should be now reassigned correctly for partner owned storages.

Thanks again for the feedback, and if you still see any problems with the calculations, please share. For now, this issue should be resolved.
